/**
 * Tools Index
 * 
 * Menggabungkan semua tools dari submodule dan mengekspor
 * dengan interface yang sama seperti tools.js sebelumnya.
 */

const { callGatewayEndpoint, isWriteOperation } = require('./gateway');
const { Logger } = require('../../../utils/logger');
const logger = Logger;
const aiConfig = require('../../../config/ai');

const {
  searchHRCandidates, createHRCandidate, updateHRCandidate, deleteHRCandidate, getHRCandidate,
  searchHRScheduleInterviews, createHRScheduleInterview, updateHRScheduleInterview, deleteHRScheduleInterview, getHRScheduleInterview,
  searchHRInterviews, createHRInterview, updateHRInterview, deleteHRInterview, getHRInterview,
  searchHRBackgroundChecks, createHRBackgroundCheck, updateHRBackgroundCheck, deleteHRBackgroundCheck, getHRBackgroundCheck,
  searchHROnBoardDocuments, createHROnBoardDocument, updateHROnBoardDocument, deleteHROnBoardDocument, getHROnBoardDocument,
  searchHRNotes, createHRNote, updateHRNote, deleteHRNote, getHRNote,
} = require('./hr');

const {
  searchQuotations, createQuotation, updateQuotation, deleteQuotation,
  searchQuotationCustomer, createQuotationCustomer, deleteQuotationCustomer,
  searchQuotationSales, createQuotationSales, deleteQuotationSales,
  searchQuotationBankAccount, createQuotationBankAccount, deleteQuotationBankAccount,
  searchQuotationTermCondition, createQuotationTermCondition, updateQuotationTermCondition, deleteQuotationTermCondition,
  searchQuotationProducts, createQuotationProduct, updateQuotationProduct, deleteQuotationProduct,
  searchQuotationAccessory, createQuotationAccessory, updateQuotationAccessory, deleteQuotationAccessory,
  searchQuotationIsland,
} = require('./quotation');

const {
  calculateQuotationGrandTotal,
  calculateQuotationProductTotal,
  calculateQuotationAccessoryTotal,
  calculateQuotationTermConditionTotal,
  calculateQuotationCustomerTotal,
  calculateQuotationBankAccountTotal,
  calculateQuotationIslandTotal,
  calculateIUPCount,
  calculateContractorCount,
} = require('./aggregation');

const {
  searchCRMTerritory, createCRMTerritory, updateCRMTerritory, deleteCRMTerritory,
  searchCRMIUPManagement, createCRMIUPManagement, updateCRMIUPManagement, deleteCRMIUPManagement,
  searchCRMSegmentation, createCRMSegmentation, updateCRMSegmentation, deleteCRMSegmentation,
  searchCRMIUPCustomers, createCRMIUPCustomer, updateCRMIUPCustomer, deleteCRMIUPCustomer,
  searchCRMTransactions, createCRMTransaction, updateCRMTransaction, deleteCRMTransaction,
  searchCRMEmployeeDataAccess, createCRMEmployeeDataAccess, updateCRMEmployeeDataAccess, deleteCRMEmployeeDataAccess,
  searchCRMIsland, createCRMIsland, updateCRMIsland, deleteCRMIsland,
  searchCRMBrand, createCRMBrand, updateCRMBrand, deleteCRMBrand,
  searchCRMGroup, createCRMGroup, updateCRMGroup, deleteCRMGroup,
  searchCRMArea, createCRMArea, updateCRMArea, deleteCRMArea,
  searchCRMIUPZone, createCRMIUPZone, updateCRMIUPZone, deleteCRMIUPZone,
  searchCRMIUPSegmentation, createCRMIUPSegmentation, updateCRMIUPSegmentation, deleteCRMIUPSegmentation,
  searchCRMProject, createCRMProject, updateCRMProject, deleteCRMProject,
  searchCRMWorkOrder, createCRMWorkOrder, updateCRMWorkOrder, deleteCRMWorkOrder,
  searchCRMDailyTask, createCRMDailyTask, updateCRMDailyTask, deleteCRMDailyTask,
  searchCRMIUPContractor, createCRMIUPContractor, updateCRMIUPContractor, deleteCRMIUPContractor,
  searchCRMIUPRkab, createCRMIUPRkab, updateCRMIUPRkab, deleteCRMIUPRkab,
  searchCRMIUPBrandUnit, createCRMIUPBrandUnit, updateCRMIUPBrandUnit, deleteCRMIUPBrandUnit,
  searchCRMIUPSurvey, getCRMIUPSurvey, createCRMIUPSurvey, updateCRMIUPSurvey, deleteCRMIUPSurvey,
  getCRMCustomer360,
  searchCRMSalesStage,
} = require('./crm');

const { searchEmployeeCompany, searchEmployeeDepartment, searchEmployeeTitle } = require('./employee');

const { searchPowerBIDashboard, searchPowerBICategory, searchPowerBIManage } = require('./powerbi');

const { searchECatalogProducts } = require('./ecatalog');

const {
  searchSSOCompanies,
  createSSOCompany,
  deleteSSOCompany,
  searchSSODepartments,
  createSSODepartment,
  deleteSSODepartment,
  searchSSOTitles,
  createSSOTitle,
  deleteSSOTitle,
  searchSSOMenus,
  createSSOMenu,
  deleteSSOMenu,
  searchSSOSystems,
  createSSOSystem,
  deleteSSOSystem,
  searchSSOGroups,
  createSSOGroup,
  deleteSSOGroup,
  getSSOUserProfile,
} = require('./sso');

const {
  searchROEQuotes, getROEQuote, createROEQuote, updateROEQuote, deleteROEQuote,
  calculateROE, updateROEOperational, updateROECost, updateROEFinancial,
  calculateNetIncome, calculateEquity, calculateROA, calculateFinanceROE,
  searchROEUnitPurchases, getROEUnitPurchase, createROEUnitPurchase, updateROEUnitPurchase, deleteROEUnitPurchase,
  searchROEListCompare, createROEListCompare, deleteROEListCompare,
  searchROEHaulingPrice, getROEHaulingPrice, createROEHaulingPrice, updateROEHaulingPrice, deleteROEHaulingPrice,
} = require('./roe');

const {
  searchNSPurchaseOrders, createNSPurchaseOrder, updateNSPurchaseOrder,
  getNSPurchaseOrderDetail, syncNSPurchaseOrders,
  searchNSSalesOrders, createNSSalesOrder, updateNSSalesOrder,
  getNSSalesOrderDetail, syncNSSalesOrders,
  searchNSFaktur, createNSFaktur, updateNSFaktur, deleteNSFaktur, getNSFaktur,
  searchNSItems, syncNSItems,
  searchNSVendors, syncNSVendors,
  searchNSCustomers, createNSCustomer,
  searchNSInvoiceSalesOrders, syncNSInvoiceSalesOrders,
  searchNSSubsidiary, createNSSubsidiary, updateNSSubsidiary, deleteNSSubsidiary,
  searchNSReference, createNSReference, updateNSReference, deleteNSReference,
  searchNSBillPayment, getNSBillPayment,
  searchNSQuotation, createNSQuotation, updateNSQuotation, getNSQuotation,
  searchNSLocations, syncNSLocations,
  searchNSDepartments, syncNSDepartments,
  searchNSClasses,
  searchNSTerms,
  searchNSPOStatus, createNSPOStatus, deleteNSPOStatus,
  searchNSItemType, createNSItemType, deleteNSItemType,
  searchNSAttachFile,
} = require('./netsuite');

const {
  searchEPCMasterCategory, createEPCMasterCategory, updateEPCMasterCategory, deleteEPCMasterCategory,
  searchEPCCategories, createEPCCategory, updateEPCCategory, deleteEPCCategory,
  searchEPCTypeCategory, createEPCTypeCategory, updateEPCTypeCategory, deleteEPCTypeCategory,
  searchEPCUnits, createEPCUnit, updateEPCUnit, deleteEPCUnit,
  searchEPCItemCategory, createEPCItemCategory, updateEPCItemCategory, deleteEPCItemCategory,
  searchEPCProducts, createEPCProduct, updateEPCProduct, deleteEPCProduct,
  searchEPCDokumen, createEPCDokumen, updateEPCDokumen, deleteEPCDokumen,
  searchEPCMasterItems, createEPCMasterItem, updateEPCMasterItem, deleteEPCMasterItem,
  searchEPCPartsCatalog,
  searchEPCVINCustomer, createEPCVINCustomer,
  searchEPCTransactionOrder, createEPCTransactionOrder, updateEPCTransactionOrder, deleteEPCTransactionOrder,
} = require('./epc');

const { summarizeData } = require('./summarize');

const {
  memorySave,
  memorySearch,
  memoryDelete,
  analyzeToolResult,
} = require('./memory');

/**
 * Tool to Module Mapping
 */
const TOOL_MODULE_MAP = {
  [searchHRCandidates.name]: ['HRM'],
  [createHRCandidate.name]: ['HRM'],
  [updateHRCandidate.name]: ['HRM'],
  [deleteHRCandidate.name]: ['HRM'],
  [getHRCandidate.name]: ['HRM'],
  [searchHRScheduleInterviews.name]: ['HRM'],
  [createHRScheduleInterview.name]: ['HRM'],
  [updateHRScheduleInterview.name]: ['HRM'],
  [deleteHRScheduleInterview.name]: ['HRM'],
  [getHRScheduleInterview.name]: ['HRM'],
  [searchHRInterviews.name]: ['HRM'],
  [createHRInterview.name]: ['HRM'],
  [updateHRInterview.name]: ['HRM'],
  [deleteHRInterview.name]: ['HRM'],
  [getHRInterview.name]: ['HRM'],
  [searchHRBackgroundChecks.name]: ['HRM'],
  [createHRBackgroundCheck.name]: ['HRM'],
  [updateHRBackgroundCheck.name]: ['HRM'],
  [deleteHRBackgroundCheck.name]: ['HRM'],
  [getHRBackgroundCheck.name]: ['HRM'],
  [searchHROnBoardDocuments.name]: ['HRM'],
  [createHROnBoardDocument.name]: ['HRM'],
  [updateHROnBoardDocument.name]: ['HRM'],
  [deleteHROnBoardDocument.name]: ['HRM'],
  [getHROnBoardDocument.name]: ['HRM'],
  [searchHRNotes.name]: ['HRM'],
  [createHRNote.name]: ['HRM'],
  [updateHRNote.name]: ['HRM'],
  [deleteHRNote.name]: ['HRM'],
  [getHRNote.name]: ['HRM'],
  [searchEmployeeCompany.name]: ['User Management', 'HR'],
  [searchEmployeeDepartment.name]: ['User Management', 'HR'],
  [searchEmployeeTitle.name]: ['User Management', 'HR'],
  [searchQuotations.name]: ['Quotation'],
  [createQuotation.name]: ['Quotation'],
  [updateQuotation.name]: ['Quotation'],
  [deleteQuotation.name]: ['Quotation'],
  [searchQuotationCustomer.name]: ['Quotation'],
  [createQuotationCustomer.name]: ['Quotation'],
  [deleteQuotationCustomer.name]: ['Quotation'],
  [searchQuotationSales.name]: ['Quotation'],
  [createQuotationSales.name]: ['Quotation'],
  [deleteQuotationSales.name]: ['Quotation'],
  [searchQuotationBankAccount.name]: ['Quotation'],
  [createQuotationBankAccount.name]: ['Quotation'],
  [deleteQuotationBankAccount.name]: ['Quotation'],
  [searchQuotationTermCondition.name]: ['Quotation'],
  [createQuotationTermCondition.name]: ['Quotation'],
  [updateQuotationTermCondition.name]: ['Quotation'],
  [deleteQuotationTermCondition.name]: ['Quotation'],
  [searchQuotationProducts.name]: ['Quotation'],
  [createQuotationProduct.name]: ['Quotation'],
  [updateQuotationProduct.name]: ['Quotation'],
  [deleteQuotationProduct.name]: ['Quotation'],
  [searchQuotationAccessory.name]: ['Quotation'],
  [createQuotationAccessory.name]: ['Quotation'],
  [updateQuotationAccessory.name]: ['Quotation'],
  [deleteQuotationAccessory.name]: ['Quotation'],
  [searchQuotationIsland.name]: ['Quotation'],
  [calculateQuotationGrandTotal.name]: ['Quotation'],
  [calculateQuotationProductTotal.name]: ['Quotation'],
  [calculateQuotationAccessoryTotal.name]: ['Quotation'],
  [calculateQuotationTermConditionTotal.name]: ['Quotation'],
  [calculateQuotationCustomerTotal.name]: ['Quotation'],
  [calculateQuotationBankAccountTotal.name]: ['Quotation'],
  [calculateQuotationIslandTotal.name]: ['Quotation'],
  [searchPowerBIDashboard.name]: ['Power BI'],
  [searchPowerBICategory.name]: ['Power BI'],
  [searchPowerBIManage.name]: ['Power BI'],
  [searchCRMTerritory.name]: ['CRM'],
  [createCRMTerritory.name]: ['CRM'],
  [updateCRMTerritory.name]: ['CRM'],
  [deleteCRMTerritory.name]: ['CRM'],
  [searchCRMIUPManagement.name]: ['CRM'],
  [createCRMIUPManagement.name]: ['CRM'],
  [updateCRMIUPManagement.name]: ['CRM'],
  [deleteCRMIUPManagement.name]: ['CRM'],
  [searchCRMSegmentation.name]: ['CRM'],
  [createCRMSegmentation.name]: ['CRM'],
  [updateCRMSegmentation.name]: ['CRM'],
  [deleteCRMSegmentation.name]: ['CRM'],
  [searchCRMIUPCustomers.name]: ['CRM'],
  [createCRMIUPCustomer.name]: ['CRM'],
  [updateCRMIUPCustomer.name]: ['CRM'],
  [deleteCRMIUPCustomer.name]: ['CRM'],
  [searchCRMTransactions.name]: ['CRM'],
  [createCRMTransaction.name]: ['CRM'],
  [updateCRMTransaction.name]: ['CRM'],
  [deleteCRMTransaction.name]: ['CRM'],
  [searchCRMEmployeeDataAccess.name]: ['CRM'],
  [createCRMEmployeeDataAccess.name]: ['CRM'],
  [updateCRMEmployeeDataAccess.name]: ['CRM'],
  [deleteCRMEmployeeDataAccess.name]: ['CRM'],
  [searchCRMIsland.name]: ['CRM'],
  [createCRMIsland.name]: ['CRM'],
  [updateCRMIsland.name]: ['CRM'],
  [deleteCRMIsland.name]: ['CRM'],
  [searchCRMBrand.name]: ['CRM'],
  [createCRMBrand.name]: ['CRM'],
  [updateCRMBrand.name]: ['CRM'],
  [deleteCRMBrand.name]: ['CRM'],
  [searchCRMGroup.name]: ['CRM'],
  [createCRMGroup.name]: ['CRM'],
  [updateCRMGroup.name]: ['CRM'],
  [deleteCRMGroup.name]: ['CRM'],
  [searchCRMArea.name]: ['CRM'],
  [createCRMArea.name]: ['CRM'],
  [updateCRMArea.name]: ['CRM'],
  [deleteCRMArea.name]: ['CRM'],
  [searchCRMIUPZone.name]: ['CRM'],
  [createCRMIUPZone.name]: ['CRM'],
  [updateCRMIUPZone.name]: ['CRM'],
  [deleteCRMIUPZone.name]: ['CRM'],
  [searchCRMIUPSegmentation.name]: ['CRM'],
  [createCRMIUPSegmentation.name]: ['CRM'],
  [updateCRMIUPSegmentation.name]: ['CRM'],
  [deleteCRMIUPSegmentation.name]: ['CRM'],
  [searchCRMProject.name]: ['CRM'],
  [createCRMProject.name]: ['CRM'],
  [updateCRMProject.name]: ['CRM'],
  [deleteCRMProject.name]: ['CRM'],
  [searchCRMWorkOrder.name]: ['CRM', 'Work Order'],
  [createCRMWorkOrder.name]: ['CRM', 'Work Order'],
  [updateCRMWorkOrder.name]: ['CRM', 'Work Order'],
  [deleteCRMWorkOrder.name]: ['CRM', 'Work Order'],
  [searchCRMDailyTask.name]: ['CRM'],
  [createCRMDailyTask.name]: ['CRM'],
  [updateCRMDailyTask.name]: ['CRM'],
  [deleteCRMDailyTask.name]: ['CRM'],
  [searchCRMIUPContractor.name]: ['CRM'],
  [createCRMIUPContractor.name]: ['CRM'],
  [updateCRMIUPContractor.name]: ['CRM'],
  [deleteCRMIUPContractor.name]: ['CRM'],
  [searchCRMIUPRkab.name]: ['CRM'],
  [createCRMIUPRkab.name]: ['CRM'],
  [updateCRMIUPRkab.name]: ['CRM'],
  [deleteCRMIUPRkab.name]: ['CRM'],
  [searchCRMIUPBrandUnit.name]: ['CRM'],
  [createCRMIUPBrandUnit.name]: ['CRM'],
  [updateCRMIUPBrandUnit.name]: ['CRM'],
  [deleteCRMIUPBrandUnit.name]: ['CRM'],
  [searchCRMIUPSurvey.name]: ['CRM'],
  [getCRMIUPSurvey.name]: ['CRM'],
  [createCRMIUPSurvey.name]: ['CRM'],
  [updateCRMIUPSurvey.name]: ['CRM'],
  [deleteCRMIUPSurvey.name]: ['CRM'],
  [getCRMCustomer360.name]: ['CRM'],
  [searchCRMSalesStage.name]: ['CRM'],
  [calculateIUPCount.name]: ['CRM'],
  [calculateContractorCount.name]: ['CRM'],
  [searchECatalogProducts.name]: ['eCatalog', 'Product'],
  [searchSSOCompanies.name]: ['User Management'],
  [createSSOCompany.name]: ['User Management'],
  [deleteSSOCompany.name]: ['User Management'],
  [searchSSODepartments.name]: ['User Management'],
  [createSSODepartment.name]: ['User Management'],
  [deleteSSODepartment.name]: ['User Management'],
  [searchSSOTitles.name]: ['User Management'],
  [createSSOTitle.name]: ['User Management'],
  [deleteSSOTitle.name]: ['User Management'],
  [searchSSOMenus.name]: ['User Management'],
  [createSSOMenu.name]: ['User Management'],
  [deleteSSOMenu.name]: ['User Management'],
  [searchSSOSystems.name]: ['User Management'],
  [createSSOSystem.name]: ['User Management'],
  [deleteSSOSystem.name]: ['User Management'],
  [searchSSOGroups.name]: ['User Management'],
  [createSSOGroup.name]: ['User Management'],
  [deleteSSOGroup.name]: ['User Management'],
  [getSSOUserProfile.name]: ['User Management'],
  [searchROEQuotes.name]: ['ROA ROE Calculate'],
  [getROEQuote.name]: ['ROA ROE Calculate'],
  [createROEQuote.name]: ['ROA ROE Calculate'],
  [updateROEQuote.name]: ['ROA ROE Calculate'],
  [deleteROEQuote.name]: ['ROA ROE Calculate'],
  [calculateROE.name]: ['ROA ROE Calculate'],
  [updateROEOperational.name]: ['ROA ROE Calculate'],
  [updateROECost.name]: ['ROA ROE Calculate'],
  [updateROEFinancial.name]: ['ROA ROE Calculate'],
  [calculateNetIncome.name]: ['ROA ROE Calculate'],
  [calculateEquity.name]: ['ROA ROE Calculate'],
  [calculateROA.name]: ['ROA ROE Calculate'],
  [searchROEUnitPurchases.name]: ['ROA ROE Calculate'],
  [getROEUnitPurchase.name]: ['ROA ROE Calculate'],
  [createROEUnitPurchase.name]: ['ROA ROE Calculate'],
  [updateROEUnitPurchase.name]: ['ROA ROE Calculate'],
  [deleteROEUnitPurchase.name]: ['ROA ROE Calculate'],
  [searchROEListCompare.name]: ['ROA ROE Calculate'],
  [createROEListCompare.name]: ['ROA ROE Calculate'],
  [deleteROEListCompare.name]: ['ROA ROE Calculate'],
  [searchROEHaulingPrice.name]: ['ROA ROE Calculate'],
  [getROEHaulingPrice.name]: ['ROA ROE Calculate'],
  [createROEHaulingPrice.name]: ['ROA ROE Calculate'],
  [updateROEHaulingPrice.name]: ['ROA ROE Calculate'],
  [deleteROEHaulingPrice.name]: ['ROA ROE Calculate'],
  [searchNSPurchaseOrders.name]: ['Netsuite', 'Purchase Order'],
  [createNSPurchaseOrder.name]: ['Netsuite', 'Purchase Order'],
  [updateNSPurchaseOrder.name]: ['Netsuite', 'Purchase Order'],
  [getNSPurchaseOrderDetail.name]: ['Netsuite', 'Purchase Order'],
  [syncNSPurchaseOrders.name]: ['Netsuite', 'Purchase Order'],
  [searchNSSalesOrders.name]: ['Netsuite', 'Sales Order'],
  [createNSSalesOrder.name]: ['Netsuite', 'Sales Order'],
  [updateNSSalesOrder.name]: ['Netsuite', 'Sales Order'],
  [getNSSalesOrderDetail.name]: ['Netsuite', 'Sales Order'],
  [syncNSSalesOrders.name]: ['Netsuite', 'Sales Order'],
  [searchNSFaktur.name]: ['Netsuite'],
  [createNSFaktur.name]: ['Netsuite'],
  [updateNSFaktur.name]: ['Netsuite'],
  [deleteNSFaktur.name]: ['Netsuite'],
  [getNSFaktur.name]: ['Netsuite'],
  [searchNSItems.name]: ['Netsuite'],
  [syncNSItems.name]: ['Netsuite'],
  [searchNSVendors.name]: ['Netsuite'],
  [syncNSVendors.name]: ['Netsuite'],
  [searchNSCustomers.name]: ['Netsuite'],
  [createNSCustomer.name]: ['Netsuite'],
  [searchNSInvoiceSalesOrders.name]: ['Netsuite'],
  [syncNSInvoiceSalesOrders.name]: ['Netsuite'],
  [searchNSSubsidiary.name]: ['Netsuite'],
  [createNSSubsidiary.name]: ['Netsuite'],
  [updateNSSubsidiary.name]: ['Netsuite'],
  [deleteNSSubsidiary.name]: ['Netsuite'],
  [searchNSReference.name]: ['Netsuite'],
  [createNSReference.name]: ['Netsuite'],
  [updateNSReference.name]: ['Netsuite'],
  [deleteNSReference.name]: ['Netsuite'],
  [searchNSBillPayment.name]: ['Netsuite'],
  [getNSBillPayment.name]: ['Netsuite'],
  [searchNSQuotation.name]: ['Netsuite'],
  [createNSQuotation.name]: ['Netsuite'],
  [updateNSQuotation.name]: ['Netsuite'],
  [getNSQuotation.name]: ['Netsuite'],
  [searchNSLocations.name]: ['Netsuite'],
  [syncNSLocations.name]: ['Netsuite'],
  [searchNSDepartments.name]: ['Netsuite'],
  [syncNSDepartments.name]: ['Netsuite'],
  [searchNSClasses.name]: ['Netsuite'],
  [searchNSTerms.name]: ['Netsuite'],
  [searchNSPOStatus.name]: ['Netsuite'],
  [createNSPOStatus.name]: ['Netsuite'],
  [deleteNSPOStatus.name]: ['Netsuite'],
  [searchNSItemType.name]: ['Netsuite'],
  [createNSItemType.name]: ['Netsuite'],
  [deleteNSItemType.name]: ['Netsuite'],
  [searchNSAttachFile.name]: ['Netsuite'],
  [searchEPCMasterCategory.name]: ['EPC'],
  [createEPCMasterCategory.name]: ['EPC'],
  [updateEPCMasterCategory.name]: ['EPC'],
  [deleteEPCMasterCategory.name]: ['EPC'],
  [searchEPCCategories.name]: ['EPC'],
  [createEPCCategory.name]: ['EPC'],
  [updateEPCCategory.name]: ['EPC'],
  [deleteEPCCategory.name]: ['EPC'],
  [searchEPCTypeCategory.name]: ['EPC'],
  [createEPCTypeCategory.name]: ['EPC'],
  [updateEPCTypeCategory.name]: ['EPC'],
  [deleteEPCTypeCategory.name]: ['EPC'],
  [searchEPCUnits.name]: ['EPC'],
  [createEPCUnit.name]: ['EPC'],
  [updateEPCUnit.name]: ['EPC'],
  [deleteEPCUnit.name]: ['EPC'],
  [searchEPCItemCategory.name]: ['EPC'],
  [createEPCItemCategory.name]: ['EPC'],
  [updateEPCItemCategory.name]: ['EPC'],
  [deleteEPCItemCategory.name]: ['EPC'],
  [searchEPCProducts.name]: ['EPC'],
  [createEPCProduct.name]: ['EPC'],
  [updateEPCProduct.name]: ['EPC'],
  [deleteEPCProduct.name]: ['EPC'],
  [searchEPCDokumen.name]: ['EPC'],
  [createEPCDokumen.name]: ['EPC'],
  [updateEPCDokumen.name]: ['EPC'],
  [deleteEPCDokumen.name]: ['EPC'],
  [searchEPCMasterItems.name]: ['EPC'],
  [createEPCMasterItem.name]: ['EPC'],
  [updateEPCMasterItem.name]: ['EPC'],
  [deleteEPCMasterItem.name]: ['EPC'],
  [searchEPCPartsCatalog.name]: ['EPC'],
  [searchEPCVINCustomer.name]: ['EPC'],
  [createEPCVINCustomer.name]: ['EPC'],
  [searchEPCTransactionOrder.name]: ['EPC'],
  [createEPCTransactionOrder.name]: ['EPC'],
  [updateEPCTransactionOrder.name]: ['EPC'],
  [deleteEPCTransactionOrder.name]: ['EPC'],
  [summarizeData.name]: ['GLOBAL'],
  [memorySave.name]: ['GLOBAL'],
  [memorySearch.name]: ['GLOBAL'],
  [memoryDelete.name]: ['GLOBAL'],
  [callGatewayEndpoint.name]: ['System'],
};

/**
 * Tool to Permission Mapping for MCP
 */
const TOOL_PERMISSION_MAP = {};
// Auto-generate mapping from TOOL_MODULE_MAP for simplicity:
// First element of allowed modules becomes menuKey, default action is 'read'
for (const [toolName, modules] of Object.entries(TOOL_MODULE_MAP)) {
  TOOL_PERMISSION_MAP[toolName] = { 
    menuKey: modules[0], 
    action: 'read' 
  };
}

// ═══════════════════════════════════════════════════════════════
//  Tools Registry — semua tool object, digunakan oleh getToolsForLangChain & executeTool
// ═══════════════════════════════════════════════════════════════

const toolsRegistry = {
  [callGatewayEndpoint.name]: callGatewayEndpoint,
  [searchHRCandidates.name]: searchHRCandidates,
  [createHRCandidate.name]: createHRCandidate,
  [updateHRCandidate.name]: updateHRCandidate,
  [deleteHRCandidate.name]: deleteHRCandidate,
  [getHRCandidate.name]: getHRCandidate,
  [searchHRScheduleInterviews.name]: searchHRScheduleInterviews,
  [createHRScheduleInterview.name]: createHRScheduleInterview,
  [updateHRScheduleInterview.name]: updateHRScheduleInterview,
  [deleteHRScheduleInterview.name]: deleteHRScheduleInterview,
  [getHRScheduleInterview.name]: getHRScheduleInterview,
  [searchHRInterviews.name]: searchHRInterviews,
  [createHRInterview.name]: createHRInterview,
  [updateHRInterview.name]: updateHRInterview,
  [deleteHRInterview.name]: deleteHRInterview,
  [getHRInterview.name]: getHRInterview,
  [searchHRBackgroundChecks.name]: searchHRBackgroundChecks,
  [createHRBackgroundCheck.name]: createHRBackgroundCheck,
  [updateHRBackgroundCheck.name]: updateHRBackgroundCheck,
  [deleteHRBackgroundCheck.name]: deleteHRBackgroundCheck,
  [getHRBackgroundCheck.name]: getHRBackgroundCheck,
  [searchHROnBoardDocuments.name]: searchHROnBoardDocuments,
  [createHROnBoardDocument.name]: createHROnBoardDocument,
  [updateHROnBoardDocument.name]: updateHROnBoardDocument,
  [deleteHROnBoardDocument.name]: deleteHROnBoardDocument,
  [getHROnBoardDocument.name]: getHROnBoardDocument,
  [searchHRNotes.name]: searchHRNotes,
  [createHRNote.name]: createHRNote,
  [updateHRNote.name]: updateHRNote,
  [deleteHRNote.name]: deleteHRNote,
  [getHRNote.name]: getHRNote,
  [searchQuotations.name]: searchQuotations,
  [createQuotation.name]: createQuotation,
  [updateQuotation.name]: updateQuotation,
  [deleteQuotation.name]: deleteQuotation,
  [searchQuotationCustomer.name]: searchQuotationCustomer,
  [createQuotationCustomer.name]: createQuotationCustomer,
  [deleteQuotationCustomer.name]: deleteQuotationCustomer,
  [searchQuotationSales.name]: searchQuotationSales,
  [createQuotationSales.name]: createQuotationSales,
  [deleteQuotationSales.name]: deleteQuotationSales,
  [searchQuotationBankAccount.name]: searchQuotationBankAccount,
  [createQuotationBankAccount.name]: createQuotationBankAccount,
  [deleteQuotationBankAccount.name]: deleteQuotationBankAccount,
  [searchQuotationTermCondition.name]: searchQuotationTermCondition,
  [createQuotationTermCondition.name]: createQuotationTermCondition,
  [updateQuotationTermCondition.name]: updateQuotationTermCondition,
  [deleteQuotationTermCondition.name]: deleteQuotationTermCondition,
  [searchQuotationProducts.name]: searchQuotationProducts,
  [createQuotationProduct.name]: createQuotationProduct,
  [updateQuotationProduct.name]: updateQuotationProduct,
  [deleteQuotationProduct.name]: deleteQuotationProduct,
  [searchQuotationAccessory.name]: searchQuotationAccessory,
  [createQuotationAccessory.name]: createQuotationAccessory,
  [updateQuotationAccessory.name]: updateQuotationAccessory,
  [deleteQuotationAccessory.name]: deleteQuotationAccessory,
  [searchQuotationIsland.name]: searchQuotationIsland,
  [searchECatalogProducts.name]: searchECatalogProducts,
  // SSO
  [searchSSOCompanies.name]: searchSSOCompanies,
  [createSSOCompany.name]: createSSOCompany,
  [deleteSSOCompany.name]: deleteSSOCompany,
  [searchSSODepartments.name]: searchSSODepartments,
  [createSSODepartment.name]: createSSODepartment,
  [deleteSSODepartment.name]: deleteSSODepartment,
  [searchSSOTitles.name]: searchSSOTitles,
  [createSSOTitle.name]: createSSOTitle,
  [deleteSSOTitle.name]: deleteSSOTitle,
  [searchSSOMenus.name]: searchSSOMenus,
  [createSSOMenu.name]: createSSOMenu,
  [deleteSSOMenu.name]: deleteSSOMenu,
  [searchSSOSystems.name]: searchSSOSystems,
  [createSSOSystem.name]: createSSOSystem,
  [deleteSSOSystem.name]: deleteSSOSystem,
  [searchSSOGroups.name]: searchSSOGroups,
  [createSSOGroup.name]: createSSOGroup,
  [deleteSSOGroup.name]: deleteSSOGroup,
  [getSSOUserProfile.name]: getSSOUserProfile,
  // ROE
  [searchROEQuotes.name]: searchROEQuotes,
  [getROEQuote.name]: getROEQuote,
  [createROEQuote.name]: createROEQuote,
  [updateROEQuote.name]: updateROEQuote,
  [deleteROEQuote.name]: deleteROEQuote,
  [calculateROE.name]: calculateROE,
  [updateROEOperational.name]: updateROEOperational,
  [updateROECost.name]: updateROECost,
  [updateROEFinancial.name]: updateROEFinancial,
  [calculateNetIncome.name]: calculateNetIncome,
  [calculateEquity.name]: calculateEquity,
  [calculateROA.name]: calculateROA,
  [calculateFinanceROE.name]: calculateFinanceROE,
  [searchROEUnitPurchases.name]: searchROEUnitPurchases,
  [getROEUnitPurchase.name]: getROEUnitPurchase,
  [createROEUnitPurchase.name]: createROEUnitPurchase,
  [updateROEUnitPurchase.name]: updateROEUnitPurchase,
  [deleteROEUnitPurchase.name]: deleteROEUnitPurchase,
  [searchROEListCompare.name]: searchROEListCompare,
  [createROEListCompare.name]: createROEListCompare,
  [deleteROEListCompare.name]: deleteROEListCompare,
  [searchROEHaulingPrice.name]: searchROEHaulingPrice,
  [getROEHaulingPrice.name]: getROEHaulingPrice,
  [createROEHaulingPrice.name]: createROEHaulingPrice,
  [updateROEHaulingPrice.name]: updateROEHaulingPrice,
  [deleteROEHaulingPrice.name]: deleteROEHaulingPrice,
  // CRM
  [searchCRMTerritory.name]: searchCRMTerritory,
  [createCRMTerritory.name]: createCRMTerritory,
  [updateCRMTerritory.name]: updateCRMTerritory,
  [deleteCRMTerritory.name]: deleteCRMTerritory,
  [searchCRMIUPManagement.name]: searchCRMIUPManagement,
  [createCRMIUPManagement.name]: createCRMIUPManagement,
  [updateCRMIUPManagement.name]: updateCRMIUPManagement,
  [deleteCRMIUPManagement.name]: deleteCRMIUPManagement,
  [searchCRMSegmentation.name]: searchCRMSegmentation,
  [createCRMSegmentation.name]: createCRMSegmentation,
  [updateCRMSegmentation.name]: updateCRMSegmentation,
  [deleteCRMSegmentation.name]: deleteCRMSegmentation,
  [searchCRMIUPCustomers.name]: searchCRMIUPCustomers,
  [createCRMIUPCustomer.name]: createCRMIUPCustomer,
  [updateCRMIUPCustomer.name]: updateCRMIUPCustomer,
  [deleteCRMIUPCustomer.name]: deleteCRMIUPCustomer,
  [searchCRMTransactions.name]: searchCRMTransactions,
  [createCRMTransaction.name]: createCRMTransaction,
  [updateCRMTransaction.name]: updateCRMTransaction,
  [deleteCRMTransaction.name]: deleteCRMTransaction,
  [searchCRMEmployeeDataAccess.name]: searchCRMEmployeeDataAccess,
  [createCRMEmployeeDataAccess.name]: createCRMEmployeeDataAccess,
  [updateCRMEmployeeDataAccess.name]: updateCRMEmployeeDataAccess,
  [deleteCRMEmployeeDataAccess.name]: deleteCRMEmployeeDataAccess,
  [searchCRMIsland.name]: searchCRMIsland,
  [createCRMIsland.name]: createCRMIsland,
  [updateCRMIsland.name]: updateCRMIsland,
  [deleteCRMIsland.name]: deleteCRMIsland,
  [searchCRMBrand.name]: searchCRMBrand,
  [createCRMBrand.name]: createCRMBrand,
  [updateCRMBrand.name]: updateCRMBrand,
  [deleteCRMBrand.name]: deleteCRMBrand,
  [searchCRMGroup.name]: searchCRMGroup,
  [createCRMGroup.name]: createCRMGroup,
  [updateCRMGroup.name]: updateCRMGroup,
  [deleteCRMGroup.name]: deleteCRMGroup,
  [searchCRMArea.name]: searchCRMArea,
  [createCRMArea.name]: createCRMArea,
  [updateCRMArea.name]: updateCRMArea,
  [deleteCRMArea.name]: deleteCRMArea,
  [searchCRMIUPZone.name]: searchCRMIUPZone,
  [createCRMIUPZone.name]: createCRMIUPZone,
  [updateCRMIUPZone.name]: updateCRMIUPZone,
  [deleteCRMIUPZone.name]: deleteCRMIUPZone,
  [searchCRMIUPSegmentation.name]: searchCRMIUPSegmentation,
  [createCRMIUPSegmentation.name]: createCRMIUPSegmentation,
  [updateCRMIUPSegmentation.name]: updateCRMIUPSegmentation,
  [deleteCRMIUPSegmentation.name]: deleteCRMIUPSegmentation,
  [searchCRMProject.name]: searchCRMProject,
  [createCRMProject.name]: createCRMProject,
  [updateCRMProject.name]: updateCRMProject,
  [deleteCRMProject.name]: deleteCRMProject,
  [searchCRMWorkOrder.name]: searchCRMWorkOrder,
  [createCRMWorkOrder.name]: createCRMWorkOrder,
  [updateCRMWorkOrder.name]: updateCRMWorkOrder,
  [deleteCRMWorkOrder.name]: deleteCRMWorkOrder,
  [searchCRMDailyTask.name]: searchCRMDailyTask,
  [createCRMDailyTask.name]: createCRMDailyTask,
  [updateCRMDailyTask.name]: updateCRMDailyTask,
  [deleteCRMDailyTask.name]: deleteCRMDailyTask,
  [searchCRMIUPContractor.name]: searchCRMIUPContractor,
  [createCRMIUPContractor.name]: createCRMIUPContractor,
  [updateCRMIUPContractor.name]: updateCRMIUPContractor,
  [deleteCRMIUPContractor.name]: deleteCRMIUPContractor,
  [searchCRMIUPRkab.name]: searchCRMIUPRkab,
  [createCRMIUPRkab.name]: createCRMIUPRkab,
  [updateCRMIUPRkab.name]: updateCRMIUPRkab,
  [deleteCRMIUPRkab.name]: deleteCRMIUPRkab,
  [searchCRMIUPBrandUnit.name]: searchCRMIUPBrandUnit,
  [createCRMIUPBrandUnit.name]: createCRMIUPBrandUnit,
  [updateCRMIUPBrandUnit.name]: updateCRMIUPBrandUnit,
  [deleteCRMIUPBrandUnit.name]: deleteCRMIUPBrandUnit,
  [searchCRMIUPSurvey.name]: searchCRMIUPSurvey,
  [getCRMIUPSurvey.name]: getCRMIUPSurvey,
  [createCRMIUPSurvey.name]: createCRMIUPSurvey,
  [updateCRMIUPSurvey.name]: updateCRMIUPSurvey,
  [deleteCRMIUPSurvey.name]: deleteCRMIUPSurvey,
  [getCRMCustomer360.name]: getCRMCustomer360,
  [searchCRMSalesStage.name]: searchCRMSalesStage,
  // Netsuite
  [searchNSPurchaseOrders.name]: searchNSPurchaseOrders,
  [createNSPurchaseOrder.name]: createNSPurchaseOrder,
  [updateNSPurchaseOrder.name]: updateNSPurchaseOrder,
  [getNSPurchaseOrderDetail.name]: getNSPurchaseOrderDetail,
  [syncNSPurchaseOrders.name]: syncNSPurchaseOrders,
  [searchNSSalesOrders.name]: searchNSSalesOrders,
  [createNSSalesOrder.name]: createNSSalesOrder,
  [updateNSSalesOrder.name]: updateNSSalesOrder,
  [getNSSalesOrderDetail.name]: getNSSalesOrderDetail,
  [syncNSSalesOrders.name]: syncNSSalesOrders,
  [searchNSFaktur.name]: searchNSFaktur,
  [createNSFaktur.name]: createNSFaktur,
  [updateNSFaktur.name]: updateNSFaktur,
  [deleteNSFaktur.name]: deleteNSFaktur,
  [getNSFaktur.name]: getNSFaktur,
  [searchNSItems.name]: searchNSItems,
  [syncNSItems.name]: syncNSItems,
  [searchNSVendors.name]: searchNSVendors,
  [syncNSVendors.name]: syncNSVendors,
  [searchNSCustomers.name]: searchNSCustomers,
  [createNSCustomer.name]: createNSCustomer,
  [searchNSInvoiceSalesOrders.name]: searchNSInvoiceSalesOrders,
  [syncNSInvoiceSalesOrders.name]: syncNSInvoiceSalesOrders,
  [searchNSSubsidiary.name]: searchNSSubsidiary,
  [createNSSubsidiary.name]: createNSSubsidiary,
  [updateNSSubsidiary.name]: updateNSSubsidiary,
  [deleteNSSubsidiary.name]: deleteNSSubsidiary,
  [searchNSReference.name]: searchNSReference,
  [createNSReference.name]: createNSReference,
  [updateNSReference.name]: updateNSReference,
  [deleteNSReference.name]: deleteNSReference,
  [searchNSBillPayment.name]: searchNSBillPayment,
  [getNSBillPayment.name]: getNSBillPayment,
  [searchNSQuotation.name]: searchNSQuotation,
  [createNSQuotation.name]: createNSQuotation,
  [updateNSQuotation.name]: updateNSQuotation,
  [getNSQuotation.name]: getNSQuotation,
  [searchNSLocations.name]: searchNSLocations,
  [syncNSLocations.name]: syncNSLocations,
  [searchNSDepartments.name]: searchNSDepartments,
  [syncNSDepartments.name]: syncNSDepartments,
  [searchNSClasses.name]: searchNSClasses,
  [searchNSTerms.name]: searchNSTerms,
  [searchNSPOStatus.name]: searchNSPOStatus,
  [createNSPOStatus.name]: createNSPOStatus,
  [deleteNSPOStatus.name]: deleteNSPOStatus,
  [searchNSItemType.name]: searchNSItemType,
  [createNSItemType.name]: createNSItemType,
  [deleteNSItemType.name]: deleteNSItemType,
  [searchNSAttachFile.name]: searchNSAttachFile,
  // EPC
  [searchEPCMasterCategory.name]: searchEPCMasterCategory,
  [createEPCMasterCategory.name]: createEPCMasterCategory,
  [updateEPCMasterCategory.name]: updateEPCMasterCategory,
  [deleteEPCMasterCategory.name]: deleteEPCMasterCategory,
  [searchEPCCategories.name]: searchEPCCategories,
  [createEPCCategory.name]: createEPCCategory,
  [updateEPCCategory.name]: updateEPCCategory,
  [deleteEPCCategory.name]: deleteEPCCategory,
  [searchEPCTypeCategory.name]: searchEPCTypeCategory,
  [createEPCTypeCategory.name]: createEPCTypeCategory,
  [updateEPCTypeCategory.name]: updateEPCTypeCategory,
  [deleteEPCTypeCategory.name]: deleteEPCTypeCategory,
  [searchEPCUnits.name]: searchEPCUnits,
  [createEPCUnit.name]: createEPCUnit,
  [updateEPCUnit.name]: updateEPCUnit,
  [deleteEPCUnit.name]: deleteEPCUnit,
  [searchEPCItemCategory.name]: searchEPCItemCategory,
  [createEPCItemCategory.name]: createEPCItemCategory,
  [updateEPCItemCategory.name]: updateEPCItemCategory,
  [deleteEPCItemCategory.name]: deleteEPCItemCategory,
  [searchEPCProducts.name]: searchEPCProducts,
  [createEPCProduct.name]: createEPCProduct,
  [updateEPCProduct.name]: updateEPCProduct,
  [deleteEPCProduct.name]: deleteEPCProduct,
  [searchEPCDokumen.name]: searchEPCDokumen,
  [createEPCDokumen.name]: createEPCDokumen,
  [updateEPCDokumen.name]: updateEPCDokumen,
  [deleteEPCDokumen.name]: deleteEPCDokumen,
  [searchEPCMasterItems.name]: searchEPCMasterItems,
  [createEPCMasterItem.name]: createEPCMasterItem,
  [updateEPCMasterItem.name]: updateEPCMasterItem,
  [deleteEPCMasterItem.name]: deleteEPCMasterItem,
  [searchEPCPartsCatalog.name]: searchEPCPartsCatalog,
  [searchEPCVINCustomer.name]: searchEPCVINCustomer,
  [createEPCVINCustomer.name]: createEPCVINCustomer,
  [searchEPCTransactionOrder.name]: searchEPCTransactionOrder,
  [createEPCTransactionOrder.name]: createEPCTransactionOrder,
  [updateEPCTransactionOrder.name]: updateEPCTransactionOrder,
  [deleteEPCTransactionOrder.name]: deleteEPCTransactionOrder,
  // Memory Tools
  [memorySave.name]: memorySave,
  [memorySearch.name]: memorySearch,
  [memoryDelete.name]: memoryDelete,
  // Others
  [searchEmployeeCompany.name]: searchEmployeeCompany,
  [searchEmployeeDepartment.name]: searchEmployeeDepartment,
  [searchEmployeeTitle.name]: searchEmployeeTitle,
  [searchPowerBIDashboard.name]: searchPowerBIDashboard,
  [searchPowerBICategory.name]: searchPowerBICategory,
  [searchPowerBIManage.name]: searchPowerBIManage,
  [calculateQuotationGrandTotal.name]: calculateQuotationGrandTotal,
  [calculateQuotationProductTotal.name]: calculateQuotationProductTotal,
  [calculateQuotationAccessoryTotal.name]: calculateQuotationAccessoryTotal,
  [calculateQuotationTermConditionTotal.name]: calculateQuotationTermConditionTotal,
  [calculateQuotationCustomerTotal.name]: calculateQuotationCustomerTotal,
  [calculateQuotationBankAccountTotal.name]: calculateQuotationBankAccountTotal,
  [calculateQuotationIslandTotal.name]: calculateQuotationIslandTotal,
  [calculateIUPCount.name]: calculateIUPCount,
  [calculateContractorCount.name]: calculateContractorCount,
};

const MAX_TOOLS = 120; // OpenAI limit is 128 — keep safe margin

/**
 * Convert tools to LangChain format (DYNAMIC — built from TOOL_MODULE_MAP)
 * - Otomatis include tools dari module yang diizinkan
 * - Jika AI_ALLOW_WRITE_ACTIONS=false, hanya kirim READ tools
 * - Prioritaskan READ tools, tambah WRITE tools jika masih ada slot
 * - callGatewayEndpoint tidak dikirim ke LangChain
 */
const getToolsForLangChain = (allowedModules) => {
  const allowWrite = aiConfig.AI_ALLOW_WRITE_ACTIONS;
  const readTools = [];
  const writeTools = [];

  for (const [toolName, modules] of Object.entries(TOOL_MODULE_MAP)) {
    if (toolName === callGatewayEndpoint.name) continue;

    // Filter by allowedModules
    if (Array.isArray(allowedModules)) {
      const isGlobal = modules.includes('GLOBAL');
      const isAllowed = modules.some(m => allowedModules.includes(m));
      if (!isGlobal && !isAllowed) continue;
    }

    const toolObj = toolsRegistry[toolName];
    if (!toolObj) continue;

    const isReadTool = toolName.startsWith('search_') || toolName.startsWith('get_') || toolName.startsWith('calculate_');
    const toolEntry = { type: 'function', function: { name: toolObj.name, description: toolObj.description, parameters: toolObj.parameters } };

    if (isReadTool) {
      readTools.push(toolEntry);
    } else if (allowWrite) {
      writeTools.push(toolEntry);
    }
  }

  // Prioritaskan READ tools dulu
  let tools = [...readTools];

  // Tambah WRITE tools kalau masih ada slot
  if (allowWrite && tools.length < MAX_TOOLS) {
    const writeBudget = MAX_TOOLS - tools.length;
    tools = tools.concat(writeTools.slice(0, writeBudget));
  }

  // Always include summarizeData
  if (!tools.find(t => t.function.name === summarizeData.name)) {
    tools.push({ type: 'function', function: { name: summarizeData.name, description: summarizeData.description, parameters: summarizeData.parameters } });
  }

  logger.info(`[Tools] getToolsForLangChain: ${tools.length} tools (${readTools.length} read, ${writeTools.length} write), allowedModules=${Array.isArray(allowedModules) ? allowedModules.length : 'ALL'}`);
  return tools;
};

/**
 * Execute tool by name
 */
const executeTool = async (toolName, parameters, authToken, mcpPermissions = null, userId = null) => {
  const tool = toolsRegistry[toolName];
  if (!tool) {
    return { success: false, message: `Tool ${toolName} tidak ditemukan` };
  }

  // Authorize MCP client execution if mcpPermissions array is provided
  if (mcpPermissions !== null) {
    const reqPerm = tool.menuKey ? { menuKey: tool.menuKey, action: tool.action || 'read' } : (TOOL_PERMISSION_MAP[toolName] || { menuKey: 'GLOBAL', action: 'read' });
    
    if (reqPerm.menuKey !== 'GLOBAL' && reqPerm.menuKey !== 'System') {
      logger.info(`[MCP] Validating tool '${toolName}'. Required: ${reqPerm.menuKey}:${reqPerm.action}`);
      const hasAccess = mcpPermissions.some(p => {
        let actions = [];
        try { actions = typeof p.actions === 'string' ? JSON.parse(p.actions) : (p.actions || []); } catch(e){}
        const match = (p.menu_key === reqPerm.menuKey || p.menu_id === reqPerm.menuKey) && actions.includes(reqPerm.action);
        if (match) {
          logger.info(`[MCP] Match found for '${toolName}': menu_key=${p.menu_key}, actions=${JSON.stringify(actions)}`);
        }
        return match;
      });
      
      if (!hasAccess) {
        logger.warn(`[MCP] Access DENIED for tool '${toolName}'.`);
        return { success: false, message: `Unauthorized: Tool requires permission for ${reqPerm.menuKey}:${reqPerm.action}` };
      }
      logger.info(`[MCP] Access GRANTED for tool '${toolName}'.`);
    }
  }

  const result = await tool.execute(parameters, authToken);

  // 🔥 MCP Feedback Learning — extract memories from tool result (async, fire & forget)
  const feedbackUserId = userId || parameters?.userId;
  if (result && feedbackUserId) {
    analyzeToolResult(toolName, parameters, result, feedbackUserId)
      .then(saved => {
        if (saved.length > 0) {
          logger.info(`[MemoryFeedback] Learned ${saved.length} memories from tool '${toolName}' for user ${feedbackUserId}`);
        }
      })
      .catch(err => {
        logger.debug(`[MemoryFeedback] Skip feedback for ${toolName}: ${err.message}`);
      });
  }

  return result;
};

module.exports = {
  getToolsForLangChain,
  executeTool,
  callGatewayEndpoint,
  searchHRCandidates,
  createHRCandidate,
  updateHRCandidate,
  deleteHRCandidate,
  getHRCandidate,
  searchHRScheduleInterviews,
  createHRScheduleInterview,
  updateHRScheduleInterview,
  deleteHRScheduleInterview,
  getHRScheduleInterview,
  searchHRInterviews,
  createHRInterview,
  updateHRInterview,
  deleteHRInterview,
  getHRInterview,
  searchHRBackgroundChecks,
  createHRBackgroundCheck,
  updateHRBackgroundCheck,
  deleteHRBackgroundCheck,
  getHRBackgroundCheck,
  searchHROnBoardDocuments,
  createHROnBoardDocument,
  updateHROnBoardDocument,
  deleteHROnBoardDocument,
  getHROnBoardDocument,
  searchHRNotes,
  createHRNote,
  updateHRNote,
  deleteHRNote,
  getHRNote,
  searchECatalogProducts,
  searchSSOCompanies,
  createSSOCompany,
  deleteSSOCompany,
  searchSSODepartments,
  createSSODepartment,
  deleteSSODepartment,
  searchSSOTitles,
  createSSOTitle,
  deleteSSOTitle,
  searchSSOMenus,
  createSSOMenu,
  deleteSSOMenu,
  searchSSOSystems,
  createSSOSystem,
  deleteSSOSystem,
  searchSSOGroups,
  createSSOGroup,
  deleteSSOGroup,
  getSSOUserProfile,
  searchROEQuotes,
  getROEQuote,
  createROEQuote,
  updateROEQuote,
  deleteROEQuote,
  calculateROE,
  updateROEOperational,
  updateROECost,
  updateROEFinancial,
  calculateNetIncome,
  calculateEquity,
  calculateROA,
  calculateFinanceROE,
  searchROEUnitPurchases,
  getROEUnitPurchase,
  createROEUnitPurchase,
  updateROEUnitPurchase,
  deleteROEUnitPurchase,
  searchROEListCompare,
  createROEListCompare,
  deleteROEListCompare,
  searchROEHaulingPrice,
  getROEHaulingPrice,
  createROEHaulingPrice,
  updateROEHaulingPrice,
  deleteROEHaulingPrice,
  searchNSPurchaseOrders,
  createNSPurchaseOrder,
  updateNSPurchaseOrder,
  getNSPurchaseOrderDetail,
  syncNSPurchaseOrders,
  searchNSSalesOrders,
  createNSSalesOrder,
  updateNSSalesOrder,
  getNSSalesOrderDetail,
  syncNSSalesOrders,
  searchNSFaktur,
  createNSFaktur,
  updateNSFaktur,
  deleteNSFaktur,
  getNSFaktur,
  searchNSItems,
  syncNSItems,
  searchNSVendors,
  syncNSVendors,
  searchNSCustomers,
  createNSCustomer,
  searchNSInvoiceSalesOrders,
  syncNSInvoiceSalesOrders,
  searchNSSubsidiary,
  createNSSubsidiary,
  updateNSSubsidiary,
  deleteNSSubsidiary,
  searchNSReference,
  createNSReference,
  updateNSReference,
  deleteNSReference,
  searchNSBillPayment,
  getNSBillPayment,
  searchNSQuotation,
  createNSQuotation,
  updateNSQuotation,
  getNSQuotation,
  searchNSLocations,
  syncNSLocations,
  searchNSDepartments,
  syncNSDepartments,
  searchNSClasses,
  searchNSTerms,
  searchNSPOStatus,
  createNSPOStatus,
  deleteNSPOStatus,
  searchNSItemType,
  createNSItemType,
  deleteNSItemType,
  searchNSAttachFile,
  searchEPCMasterCategory,
  createEPCMasterCategory,
  updateEPCMasterCategory,
  deleteEPCMasterCategory,
  searchEPCCategories,
  createEPCCategory,
  updateEPCCategory,
  deleteEPCCategory,
  searchEPCTypeCategory,
  createEPCTypeCategory,
  updateEPCTypeCategory,
  deleteEPCTypeCategory,
  searchEPCUnits,
  createEPCUnit,
  updateEPCUnit,
  deleteEPCUnit,
  searchEPCItemCategory,
  createEPCItemCategory,
  updateEPCItemCategory,
  deleteEPCItemCategory,
  searchEPCProducts,
  createEPCProduct,
  updateEPCProduct,
  deleteEPCProduct,
  searchEPCDokumen,
  createEPCDokumen,
  updateEPCDokumen,
  deleteEPCDokumen,
  searchEPCMasterItems,
  createEPCMasterItem,
  updateEPCMasterItem,
  deleteEPCMasterItem,
  searchEPCPartsCatalog,
  searchEPCVINCustomer,
  createEPCVINCustomer,
  searchEPCTransactionOrder,
  createEPCTransactionOrder,
  updateEPCTransactionOrder,
  deleteEPCTransactionOrder,
  summarizeData,
  searchPowerBIDashboard,
  searchPowerBICategory,
  searchPowerBIManage,
  searchQuotations,
  createQuotation,
  updateQuotation,
  deleteQuotation,
  searchQuotationCustomer,
  createQuotationCustomer,
  deleteQuotationCustomer,
  searchQuotationSales,
  createQuotationSales,
  deleteQuotationSales,
  searchQuotationBankAccount,
  createQuotationBankAccount,
  deleteQuotationBankAccount,
  searchQuotationTermCondition,
  createQuotationTermCondition,
  updateQuotationTermCondition,
  deleteQuotationTermCondition,
  searchQuotationProducts,
  createQuotationProduct,
  updateQuotationProduct,
  deleteQuotationProduct,
  searchQuotationAccessory,
  createQuotationAccessory,
  updateQuotationAccessory,
  deleteQuotationAccessory,
  searchQuotationIsland,
  searchCRMTerritory,
  createCRMTerritory,
  updateCRMTerritory,
  deleteCRMTerritory,
  searchCRMIUPManagement,
  createCRMIUPManagement,
  updateCRMIUPManagement,
  deleteCRMIUPManagement,
  searchCRMSegmentation,
  createCRMSegmentation,
  updateCRMSegmentation,
  deleteCRMSegmentation,
  searchCRMIUPCustomers,
  createCRMIUPCustomer,
  updateCRMIUPCustomer,
  deleteCRMIUPCustomer,
  searchCRMTransactions,
  createCRMTransaction,
  updateCRMTransaction,
  deleteCRMTransaction,
  searchCRMEmployeeDataAccess,
  createCRMEmployeeDataAccess,
  updateCRMEmployeeDataAccess,
  deleteCRMEmployeeDataAccess,
  searchCRMIsland,
  createCRMIsland,
  updateCRMIsland,
  deleteCRMIsland,
  searchCRMBrand,
  createCRMBrand,
  updateCRMBrand,
  deleteCRMBrand,
  searchCRMGroup,
  createCRMGroup,
  updateCRMGroup,
  deleteCRMGroup,
  searchCRMArea,
  createCRMArea,
  updateCRMArea,
  deleteCRMArea,
  searchCRMIUPZone,
  createCRMIUPZone,
  updateCRMIUPZone,
  deleteCRMIUPZone,
  searchCRMIUPSegmentation,
  createCRMIUPSegmentation,
  updateCRMIUPSegmentation,
  deleteCRMIUPSegmentation,
  searchCRMProject,
  createCRMProject,
  updateCRMProject,
  deleteCRMProject,
  searchCRMWorkOrder,
  createCRMWorkOrder,
  updateCRMWorkOrder,
  deleteCRMWorkOrder,
  searchCRMDailyTask,
  createCRMDailyTask,
  updateCRMDailyTask,
  deleteCRMDailyTask,
  searchCRMIUPContractor,
  createCRMIUPContractor,
  updateCRMIUPContractor,
  deleteCRMIUPContractor,
  searchCRMIUPRkab,
  createCRMIUPRkab,
  updateCRMIUPRkab,
  deleteCRMIUPRkab,
  searchCRMIUPBrandUnit,
  createCRMIUPBrandUnit,
  updateCRMIUPBrandUnit,
  deleteCRMIUPBrandUnit,
  searchCRMIUPSurvey,
  getCRMIUPSurvey,
  createCRMIUPSurvey,
  updateCRMIUPSurvey,
  deleteCRMIUPSurvey,
  getCRMCustomer360,
  searchCRMSalesStage,
  searchEmployeeCompany,
  searchEmployeeDepartment,
  searchEmployeeTitle,
  calculateQuotationGrandTotal,
  calculateQuotationProductTotal,
  calculateQuotationAccessoryTotal,
  calculateQuotationTermConditionTotal,
  calculateQuotationCustomerTotal,
  calculateQuotationBankAccountTotal,
  calculateQuotationIslandTotal,
  calculateIUPCount,
  calculateContractorCount,
  // Memory Tools
  memorySave,
  memorySearch,
  memoryDelete,
  analyzeToolResult,
};
